---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install docker
    yum: name=docker state=present
  - name: Start docker
    service: name=docker state=started
  - name: Get the dockerfile from github
    git: repo="https://github.com/leonardtia1/docker_demo1.git" dest=/tmp/dockerdir_1
  - name: Build the dockerfile
    command: docker build -t pebble:1.0 /tmp/dockerdiri_1
  - name: Run the docker image
    command: docker run -d -p 8095:8080 --name my-pebble-app pebble:1.0
