---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install docker
    yum: name=docker state=present
  - name: Start docker
    service: name=docker state=started
  - name: Get the dockerfile from github
    git: repo="https://github.com/leonardtia1/docker_demo6.git" dest=/tmp/dockerdir_6
  - name: Build the dockerfile
    command: docker build -t stutendent_registration:2.0 /tmp/dockerdir_6
  - name: Run the docker image
    command: docker run -d -p 8095:8080 --name my-stutendent_registration-app stutendent_registration:2.0
