apiVersion: v1
kind: Service
metadata:
  name: web-app-tia
  labels:
    app: web-app-tia
spec:
  selector:
    app: web-app-tia
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200

